name: .NET Core

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
  
    - uses: Azure/pipelines@v1
      with:
          azure-devops-project-url: 'https://dev.azure.com/HenriqueitAzurePipelines/Modulo%203%20-%20Pipelines%20com%20YAML'
          azure-pipeline-name: 'Modulo 3 - Pipelines com YAML' # name of the Azure pipeline to be triggered
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
          azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
