name: Sync Pull Request to Azure Boards

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - main

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'   
        github_token: '${{ secrets.GH_TOKEN }}'    
        ado_organization: 'HenriqueitAzurePipelines'
        ado_project: 'Modulo 3 - Pipelines com YAML'
        ado_wit: 'Task' 
        ado_new_state: 'To Do'
        ado_active_state: 'In Progress'
        ado_close_state: 'Done'
